server:
  port: 3000
# server.port: 3000 과 동일
# 콜론 이후에 한 칸 띄우고 쓴다.
# 들여쓰기하면 포함하고 있는 것으로 본다.

spring:
  # 프로필 설정
  #profiles:
  #  active: dev

  # 파일 업로드 설정
  servlet:
    multipart:
      maxFileSize: 20MB   # 파일 한개당 최대 용량
#      max-file-size: 20MB
      maxRequestSize: 60MB

  # 정적 자원 설정(CSS, JS, 이미지)
  web:
    resources:
      staticLocations: file:src/main/resources/static/
     # static-locations:


  #데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    #driver-class-name: 으로도 사용할 수 있다
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: SPRING6
    password: _aA123456

  # 라이브 리로드 설정
  devtools:
    livereload:
      enabled: true

  # 타임리프 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/ # 마지막에 슬래시를 포함(주의!)

# 파일 설정
  file:
    url: /upload/
    path: C:/uploads/

  # 로거 설정
logging:
  level:
    org:
      springframework:
        jdbc: trace

