/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.81
 * Generated at: 2023-11-27 03:33:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.book;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.me.dto.PageDto;
import com.me.dto.Criteria;

public final class bookList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1701054652682L));
    _jspx_dependants.put("/06.session/servletEx/pageNavi.jsp", Long.valueOf(1701047536179L));
    _jspx_dependants.put("jar:file:/C:/app/jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1700440520065L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1701054376743L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.me.dto.PageDto");
    _jspx_imports_classes.add("com.me.dto.Criteria");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005fvar_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005fvar_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005fvar_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.pointer {\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	window.onload = function() {\r\n");
      out.write("		// 요소 선택\r\n");
      out.write("		let regBtn = document.querySelector(\"#regBtn\");\r\n");
      out.write("		\r\n");
      out.write("		// 이벤트 부여\r\n");
      out.write("		regBtn.addEventListener('click', function(){\r\n");
      out.write("			location.href = \"/book/reg.jsp\";\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		searchBtn.addEventListener('click', function(){\r\n");
      out.write("			searchForm.action = \"/book/bookList\";\r\n");
      out.write("			searchForm.submit();\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("/*\r\n");
      out.write("	스크립트에서 함수 정의하는 방법\r\n");
      out.write("	function 함수명(파람0, 파람, ...);\r\n");
      out.write("*/\r\n");
      out.write("	function goview(no){\r\n");
      out.write("		location.href=\"/view?no=\" + no;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>SB Admin 2 - Tables</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom fonts for this template -->\r\n");
      out.write("<link href=\"../vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\"\r\n");
      out.write("	type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"../css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this page -->\r\n");
      out.write("<link href=\"../vendor/datatables/dataTables.bootstrap4.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Page Wrapper -->\r\n");
      out.write("	<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Sidebar -->\r\n");
      out.write("		<ul\r\n");
      out.write("			class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\"\r\n");
      out.write("			id=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Sidebar - Brand -->\r\n");
      out.write("			<a\r\n");
      out.write("				class=\"sidebar-brand d-flex align-items-center justify-content-center\"\r\n");
      out.write("				href=\"index.html\">\r\n");
      out.write("				<div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("					<i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sidebar-brand-text mx-3\">\r\n");
      out.write("					이대 도서관</sup>\r\n");
      out.write("				</div>\r\n");
      out.write("			</a>\r\n");
      out.write("\r\n");
      out.write("			<!-- Divider -->\r\n");
      out.write("			<hr class=\"sidebar-divider my-0\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Nav Item - Dashboard -->\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.html\">\r\n");
      out.write("					<i class=\"fas fa-fw fa-tachometer-alt\"></i> <span>도서목록</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("\r\n");
      out.write("			<!-- Divider -->\r\n");
      out.write("			<hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Heading -->\r\n");
      out.write("			<div class=\"sidebar-heading\">Interface</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("				data-toggle=\"collapse\" data-target=\"#collapseTwo\"\r\n");
      out.write("				aria-expanded=\"true\" aria-controls=\"collapseTwo\"> <i\r\n");
      out.write("					class=\"fas fa-fw fa-cog\"></i> <span>Components</span>\r\n");
      out.write("			</a>\r\n");
      out.write("				<div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\"\r\n");
      out.write("					data-parent=\"#accordionSidebar\">\r\n");
      out.write("					<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("						<h6 class=\"collapse-header\">Custom Components:</h6>\r\n");
      out.write("						<a class=\"collapse-item\" href=\"buttons.html\">Buttons</a> <a\r\n");
      out.write("							class=\"collapse-item\" href=\"cards.html\">Cards</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div></li>\r\n");
      out.write("\r\n");
      out.write("			<!-- Nav Item - Utilities Collapse Menu -->\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("				data-toggle=\"collapse\" data-target=\"#collapseUtilities\"\r\n");
      out.write("				aria-expanded=\"true\" aria-controls=\"collapseUtilities\"> <i\r\n");
      out.write("					class=\"fas fa-fw fa-wrench\"></i> <span>Utilities</span>\r\n");
      out.write("			</a>\r\n");
      out.write("				<div id=\"collapseUtilities\" class=\"collapse\"\r\n");
      out.write("					aria-labelledby=\"headingUtilities\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("					<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("						<h6 class=\"collapse-header\">Custom Utilities:</h6>\r\n");
      out.write("						<a class=\"collapse-item\" href=\"utilities-color.html\">Colors</a> <a\r\n");
      out.write("							class=\"collapse-item\" href=\"utilities-border.html\">Borders</a> <a\r\n");
      out.write("							class=\"collapse-item\" href=\"utilities-animation.html\">Animations</a>\r\n");
      out.write("						<a class=\"collapse-item\" href=\"utilities-other.html\">Other</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div></li>\r\n");
      out.write("\r\n");
      out.write("			<!-- Divider -->\r\n");
      out.write("			<hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Heading -->\r\n");
      out.write("			<div class=\"sidebar-heading\">Addons</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link collapsed\" href=\"#\"\r\n");
      out.write("				data-toggle=\"collapse\" data-target=\"#collapsePages\"\r\n");
      out.write("				aria-expanded=\"true\" aria-controls=\"collapsePages\"> <i\r\n");
      out.write("					class=\"fas fa-fw fa-folder\"></i> <span>Pages</span>\r\n");
      out.write("			</a>\r\n");
      out.write("				<div id=\"collapsePages\" class=\"collapse\"\r\n");
      out.write("					aria-labelledby=\"headingPages\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("					<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("						<h6 class=\"collapse-header\">Login Screens:</h6>\r\n");
      out.write("						<a class=\"collapse-item\" href=\"login.html\">Login</a> <a\r\n");
      out.write("							class=\"collapse-item\" href=\"register.html\">Register</a> <a\r\n");
      out.write("							class=\"collapse-item\" href=\"forgot-password.html\">Forgot\r\n");
      out.write("							Password</a>\r\n");
      out.write("						<div class=\"collapse-divider\"></div>\r\n");
      out.write("						<h6 class=\"collapse-header\">Other Pages:</h6>\r\n");
      out.write("						<a class=\"collapse-item\" href=\"404.html\">404 Page</a> <a\r\n");
      out.write("							class=\"collapse-item\" href=\"blank.html\">Blank Page</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div></li>\r\n");
      out.write("\r\n");
      out.write("			<!-- Nav Item - Charts -->\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"charts.html\">\r\n");
      out.write("					<i class=\"fas fa-fw fa-chart-area\"></i> <span>Charts</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("\r\n");
      out.write("			<!-- Nav Item - Tables -->\r\n");
      out.write("			<li class=\"nav-item active\"><a class=\"nav-link\"\r\n");
      out.write("				href=\"tables.html\"> <i class=\"fas fa-fw fa-table\"></i> <span>Tables</span></a>\r\n");
      out.write("			</li>\r\n");
      out.write("\r\n");
      out.write("			<!-- Divider -->\r\n");
      out.write("			<hr class=\"sidebar-divider d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("			<div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("				<button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</ul>\r\n");
      out.write("		<!-- End of Sidebar -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Content Wrapper -->\r\n");
      out.write("		<div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Main Content -->\r\n");
      out.write("			<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Topbar -->\r\n");
      out.write("				<nav\r\n");
      out.write("					class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Sidebar Toggle (Topbar) -->\r\n");
      out.write("					<form class=\"form-inline\">\r\n");
      out.write("						<button id=\"sidebarToggleTop\"\r\n");
      out.write("							class=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("							<i class=\"fa fa-bars\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<!-- Topbar Navbar -->\r\n");
      out.write("					<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("						<!-- Nav Item - Search Dropdown (Visible Only XS) -->\r\n");
      out.write("						<li class=\"nav-item dropdown no-arrow d-sm-none\"><a\r\n");
      out.write("							class=\"nav-link dropdown-toggle\" href=\"#\" id=\"searchDropdown\"\r\n");
      out.write("							role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("							aria-expanded=\"false\"> <i class=\"fas fa-search fa-fw\"></i>\r\n");
      out.write("						</a> <!-- Dropdown - Messages -->\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in\"\r\n");
      out.write("								aria-labelledby=\"searchDropdown\">\r\n");
      out.write("								<form class=\"form-inline mr-auto w-100 navbar-search\">\r\n");
      out.write("									<div class=\"input-group\">\r\n");
      out.write("										<input type=\"text\"\r\n");
      out.write("											class=\"form-control bg-light border-0 small\"\r\n");
      out.write("											placeholder=\"Search for...\" aria-label=\"Search\"\r\n");
      out.write("											aria-describedby=\"basic-addon2\">\r\n");
      out.write("										<div class=\"input-group-append\">\r\n");
      out.write("											<button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("												<i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("											</button>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<!-- Nav Item - Alerts -->\r\n");
      out.write("						<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("							class=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\"\r\n");
      out.write("							role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("							aria-expanded=\"false\"> <i class=\"fas fa-bell fa-fw\"></i> <!-- Counter - Alerts -->\r\n");
      out.write("								<span class=\"badge badge-danger badge-counter\">3+</span>\r\n");
      out.write("						</a> <!-- Dropdown - Alerts -->\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("								aria-labelledby=\"alertsDropdown\">\r\n");
      out.write("								<h6 class=\"dropdown-header\">Alerts Center</h6>\r\n");
      out.write("								<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("									<div class=\"mr-3\">\r\n");
      out.write("										<div class=\"icon-circle bg-primary\">\r\n");
      out.write("											<i class=\"fas fa-file-alt text-white\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<div class=\"small text-gray-500\">December 12, 2019</div>\r\n");
      out.write("										<span class=\"font-weight-bold\">A new monthly report is\r\n");
      out.write("											ready to download!</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("									<div class=\"mr-3\">\r\n");
      out.write("										<div class=\"icon-circle bg-success\">\r\n");
      out.write("											<i class=\"fas fa-donate text-white\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<div class=\"small text-gray-500\">December 7, 2019</div>\r\n");
      out.write("										$290.29 has been deposited into your account!\r\n");
      out.write("									</div>\r\n");
      out.write("								</a> <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("									<div class=\"mr-3\">\r\n");
      out.write("										<div class=\"icon-circle bg-warning\">\r\n");
      out.write("											<i class=\"fas fa-exclamation-triangle text-white\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<div class=\"small text-gray-500\">December 2, 2019</div>\r\n");
      out.write("										Spending Alert: We've noticed unusually high spending for your\r\n");
      out.write("										account.\r\n");
      out.write("									</div>\r\n");
      out.write("								</a> <a class=\"dropdown-item text-center small text-gray-500\"\r\n");
      out.write("									href=\"#\">Show All Alerts</a>\r\n");
      out.write("							</div></li>\r\n");
      out.write("\r\n");
      out.write("						<!-- Nav Item - Messages -->\r\n");
      out.write("						<li class=\"nav-item dropdown no-arrow mx-1\"><a\r\n");
      out.write("							class=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\"\r\n");
      out.write("							role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("							aria-expanded=\"false\"> <i class=\"fas fa-envelope fa-fw\"></i>\r\n");
      out.write("								<!-- Counter - Messages --> <span\r\n");
      out.write("								class=\"badge badge-danger badge-counter\">7</span>\r\n");
      out.write("						</a> <!-- Dropdown - Messages -->\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("								aria-labelledby=\"messagesDropdown\">\r\n");
      out.write("								<h6 class=\"dropdown-header\">Message Center</h6>\r\n");
      out.write("								<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("									<div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("										<img class=\"rounded-circle\"\r\n");
      out.write("											src=\"https://source.unsplash.com/Mv9hjnEUHR4/60x60\" alt=\"...\">\r\n");
      out.write("										<div class=\"status-indicator bg-success\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<div class=\"text-truncate\">Am I a good boy? The reason I\r\n");
      out.write("											ask is because someone told me that people say this to all\r\n");
      out.write("											dogs, even if they aren't good...</div>\r\n");
      out.write("										<div class=\"small text-gray-500\">Chicken the Dog · 2w</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</a> <a class=\"dropdown-item text-center small text-gray-500\"\r\n");
      out.write("									href=\"#\">Read More Messages</a>\r\n");
      out.write("							</div></li>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"topbar-divider d-none d-sm-block\"></div>\r\n");
      out.write("\r\n");
      out.write("						<!-- Nav Item - User Information -->\r\n");
      out.write("						<li class=\"nav-item dropdown no-arrow\"><a\r\n");
      out.write("							class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\"\r\n");
      out.write("							role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("							aria-expanded=\"false\"> <span\r\n");
      out.write("								class=\"mr-2 d-none d-lg-inline text-gray-600 small\">Douglas\r\n");
      out.write("									McGee</span> <img class=\"img-profile rounded-circle\"\r\n");
      out.write("								src=\"img/undraw_profile.svg\">\r\n");
      out.write("						</a> <!-- Dropdown - User Information -->\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("								aria-labelledby=\"userDropdown\">\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"#\"> <i\r\n");
      out.write("									class=\"fas fa-user fa-sm fa-fw mr-2 text-gray-400\"></i> Profile\r\n");
      out.write("								</a> <a class=\"dropdown-item\" href=\"#\"> <i\r\n");
      out.write("									class=\"fas fa-cogs fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("									Settings\r\n");
      out.write("								</a> <a class=\"dropdown-item\" href=\"#\"> <i\r\n");
      out.write("									class=\"fas fa-list fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("									Activity Log\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"dropdown-divider\"></div>\r\n");
      out.write("								<a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\"\r\n");
      out.write("									data-target=\"#logoutModal\"> <i\r\n");
      out.write("									class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\r\n");
      out.write("									Logout\r\n");
      out.write("								</a>\r\n");
      out.write("							</div></li>\r\n");
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("\r\n");
      out.write("				</nav>\r\n");
      out.write("				<!-- End of Topbar -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<!--  header 외부파일 인클루드 -->\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- 도서목록을 출력한다. -->\r\n");
      out.write("	<h2>도서목록</h2>\r\n");
      out.write("	<!-- Content Wrapper -->\r\n");
      out.write("	<div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("		<!-- 메인컨텐츠 영역 -->\r\n");
      out.write("		<!-- Begin Page Content -->\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Topbar Search -->\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("			<!-- DataTales Example -->\r\n");
      out.write("			<div class=\"card shadow mb-4\">\r\n");
      out.write("				<div class=\"card-header py-3\">\r\n");
      out.write("					<h6 class=\"m-0 font-weight-bold text-primary\">도서목록</h6>\r\n");
      out.write("				</div>\r\n");
      out.write("			<!-- form submit()\r\n");
      out.write("				폼이 가지고 있는 요소를 파라메터로 서버에 요청(action)을 하는 것\r\n");
      out.write("				(action)에 등록되어 있지 않은 경우 현재 페이지를 다시 요청함) -->\r\n");
      out.write("			<form name=\"searchForm\" action=\"/book/bookList\"\r\n");
      out.write("				class=\"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<select class=\"form-select\" name=\"searchField\"\r\n");
      out.write("						id=\"inputGroupSelect04\"\r\n");
      out.write("						aria-label=\"Example select with button addon\">\r\n");
      out.write("						<option selected disabled>선택</option>\r\n");
      out.write("						<!-- 선택된 요소의 value값이 서버로 넘어간다. -->\r\n");
      out.write("						<option value=\"title\"\r\n");
      out.write("							");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDto.cri.searchField eq 'title' ? 'selected' : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">제목</option>\r\n");
      out.write("						<option value=\"id\"\r\n");
      out.write("							");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDto.cri.searchField eq 'id' ? 'selected' : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">작성자</option>\r\n");
      out.write("						<option value=\"content\"\r\n");
      out.write("							");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDto.cri.searchField eq 'content' ? 'selected' : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">내용</option>\r\n");
      out.write("					</select> <input type=\"text\" name=\"searchWord\" class=\"form-control\"\r\n");
      out.write("						aria-label=\"Text input with dropdown button\">\r\n");
      out.write("					<button class=\"btn btn-outline-secondary\" type=\"submit\" id=\"searchBtn\">검색</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-dark\" id=\"regBtn\">도서등록</button>\r\n");
      out.write("					<div class=\"table-responsive\">\r\n");
      out.write("						<table class=\"table table-bordered\" width=\"100%\" cellspacing=\"0\">\r\n");
      out.write("							<thead>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th>번호</th>\r\n");
      out.write("									<th>제목</th>\r\n");
      out.write("									<th>저자</th>\r\n");
      out.write("									<th>대여여부</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("\r\n");
      out.write("								<!-- 리스트가 비어있으면 메세지 출력 -->\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<!-- 리스트가 비어있지 않다면 도서목록 출력 -->\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("						<!-- pageDto가 reqeust영역에 저정되어 있으면  -->\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function goPage(pageNo){\r\n");
      out.write("		searchForm.pageNo.vaue = 0;\r\n");
      out.write("		searchForm.submit();\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- 부트스트랩 CSS -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
/*	
	PageDto pageDto = null;
	if(request.getAttribute("pageDto") != null && !"".equals(request.getAttribute("pageDto"))){
		pageDto = (PageDto)request.getAttribute("pageDto");
	} else {
		pageDto = new PageDto(0, new Criteria());
	}
*/
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 페이지 블럭을 출력하는 방법\r\n");
      out.write("	1. 요청 컨트롤러에서 pageDto를 request영역에 저장.\r\n");
      out.write("	2. pageNavi.jsp를 리스트 페이지 블럭을 출력하고 싶은 위치에 include.\r\n");
      out.write("	3. searchForm을 생성.\r\n");
      out.write("		pageNo 요소가 있어야 함.\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("<!-- 페이지네이션 -->\r\n");
      out.write("<nav aria-label=\"...\">\r\n");
      out.write("  <ul class=\"pagination\">\r\n");
      out.write("  \r\n");
      out.write("  	<!-- 앞으로 가기 버튼 시작, disabled : 비활성화 -->\r\n");
      out.write("    <li class='page-item ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDto.prev ? \"\" : \"disabled\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\r\n");
      out.write("      <a class=\"page-link\" onclick=\"goPage(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDto.startNo -1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">&laquo;</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <!-- 앞으로 가기 버튼 끝 -->\r\n");
      out.write("    \r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 뒤로가기 버튼 시작 -->\r\n");
      out.write("    <li class='page-item ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDto.prev ? \"\" : \"disabled\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\r\n");
      out.write("      <a class=\"page-link\" onclick=\"goPage(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDto.endNo + 1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">&raquo;</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <!-- 뒤로가기 버튼 끝 -->\r\n");
      out.write("    \r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- /.container-fluid -->\r\n");
      out.write("\r\n");
      out.write("		<!-- 메인컨텐츠 영역 끝 -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End of Main Content -->\r\n");
      out.write("	<!--  footer 외부파일 인클루드 -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write(" <!-- Footer -->\r\n");
      out.write("            <footer class=\"sticky-footer bg-white\">\r\n");
      out.write("                <div class=\"container my-auto\">\r\n");
      out.write("                    <div class=\"copyright text-center my-auto\">\r\n");
      out.write("                        <span>Copyright &copy; Your Website 2020</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- End of Footer -->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of Content Wrapper -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End of Page Wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Scroll to Top Button-->\r\n");
      out.write("    <a class=\"scroll-to-top rounded\" href=\"#page-top\">\r\n");
      out.write("        <i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- Logout Modal-->\r\n");
      out.write("    <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\r\n");
      out.write("        aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\r\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">×</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">Select \"Logout\" below if you are ready to end your current session.</div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <a class=\"btn btn-primary\" href=\"login.html\">Logout</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript-->\r\n");
      out.write("    <script src=\"../vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"../vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Core plugin JavaScript-->\r\n");
      out.write("    <script src=\"../vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom scripts for all pages-->\r\n");
      out.write("    <script src=\"../js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page level plugins -->\r\n");
      out.write("    <script src=\"../vendor/datatables/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"../vendor/datatables/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page level custom scripts -->\r\n");
      out.write("    <script src=\"../js/demo/datatables-demo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<!-- 부트스트랩 js -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005fvar_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /book/bookList.jsp(111,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty list }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      // /book/bookList.jsp(111,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setVar("res");
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<tr>\r\n");
          out.write("										<td colspan=\"4\">도서목록이 존재하지 않습니다.</td>\r\n");
          out.write("									</tr>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005fvar_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /book/bookList.jsp(118,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not res }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /book/bookList.jsp(119,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/book/bookList.jsp(119,9) '${list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /book/bookList.jsp(119,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("bookDto");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("										<tr>\r\n");
            out.write("											<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bookDto.num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("											<td class=\"pointer\" onclick=\"goview(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bookDto.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(')');
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bookDto.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("											<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bookDto.author }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("											<!-- Y/N => 대여가능/대여중 -->\r\n");
            out.write("											<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bookDto.rentynStr }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("										</tr>\r\n");
            out.write("									");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /06.session/servletEx/pageNavi.jsp(51,4) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDto.startNo }", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /06.session/servletEx/pageNavi.jsp(51,4) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDto.endNo }", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /06.session/servletEx/pageNavi.jsp(51,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("i");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("	    <li class=\"page-item\">\r\n");
            out.write("	    	<!-- href=\"...\" 링크로 이동할 경우, 검색어가 유지되지 않는다. -->\r\n");
            out.write("	    	<!-- 검색어를 유지하기 위해 searchForm을 전송하는 goPage 함수를 생성. -->\r\n");
            out.write("	    	<!-- 링크를 함수호출로 변경, onClick이벤트가 발생하면 goPage()함수를 호출한다.\r\n");
            out.write("	    				함수의 파라메터로 페이지번호를 넣어주어야 한다. -->\r\n");
            out.write("	    	<a class=\"page-link ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageDto.cri.pageNo eq i ? 'active' : '' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" \r\n");
            out.write("	    		onclick=\"goPage(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\">\r\n");
            out.write("	    		");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("	    	</a>\r\n");
            out.write("	    </li>\r\n");
            out.write("    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
